
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 18 11:21:18 BRST 2016
//----------------------------------------------------

package br.uff.compilers.luacompilers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TWO_PERIOD = 37;
  public static final int FUNCTION = 13;
  public static final int PERIOD = 38;
  public static final int LESS_THAN_EQUAL = 40;
  public static final int CLOSE_PARENTHESES = 29;
  public static final int REPEAT = 5;
  public static final int FOR = 10;
  public static final int MINUS = 32;
  public static final int NOT = 47;
  public static final int AND = 45;
  public static final int SEMICOLON = 22;
  public static final int ELSEIF = 9;
  public static final int UP_CARET = 35;
  public static final int NIL = 17;
  public static final int OR = 46;
  public static final int IN = 11;
  public static final int ELLIPSIS = 20;
  public static final int OPEN_BRACKETS = 24;
  public static final int COMMA = 23;
  public static final int DIV = 34;
  public static final int UNTIL = 12;
  public static final int DIFFERENT = 44;
  public static final int PLUS = 31;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 43;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int PERCENT = 36;
  public static final int NUMBER = 49;
  public static final int GREATHER_THAN = 41;
  public static final int BREAK = 16;
  public static final int GREATHER_THAN_EQUAL = 42;
  public static final int SIGN = 30;
  public static final int TIMES = 33;
  public static final int COLON = 21;
  public static final int ELSE = 8;
  public static final int WHILE = 4;
  public static final int THEN = 7;
  public static final int CLOSE_BRACES = 27;
  public static final int END = 3;
  public static final int CLOSE_BRACKETS = 25;
  public static final int STRING = 50;
  public static final int LOCAL = 14;
  public static final int FALSE = 18;
  public static final int LESS_THAN = 39;
  public static final int OPEN_PARENTHESES = 28;
  public static final int LENGTH = 48;
  public static final int DO = 2;
  public static final int OPEN_BRACES = 26;
  public static final int IDENTIFIER = 51;
}

